apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app2-uat

resources:
  - ../../base

images:
  - name: nginx
    newTag: 1.25-alpine

replicas:
  - name: app2
    count: 2

patches:
  - path: patches/deployment-patch.yaml

configMapGenerator:
  - name: app2-html
    behavior: replace
    files:
      - index.html=html/index.html

commonLabels:
  environment: uat