apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app1-dev

resources:
  - ../../base

images:
  - name: nginx
    newTag: 1.25-alpine

replicas:
  - name: app1
    count: 1

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/service-patch.yaml

configMapGenerator:
  - name: app1-html
    behavior: replace
    files:
      - index.html=html/index.html

commonLabels:
  environment: dev