apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app1-prod

resources:
  - ../../base

images:
  - name: nginx
    newTag: 1.25-alpine  # Must match prod

replicas:
  - name: app1
    count: 3  # Active in DR

patches:
  - path: patches/deployment-patch.yaml
  - path: patches/ingress.yaml
  - path: patches/hpa.yaml
  - path: patches/pdb.yaml

configMapGenerator:
  - name: app1-html
    behavior: replace
    files:
      - index.html=html/index.html

commonLabels:
  environment: production
  site: disaster-recovery